---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data

``` {r}
unzip("activity.zip")
activity <- read.csv("activity.csv")

str(activity)

tail(activity$interval)

# Although interval is represented as integer, the integer is %H%M coded, 
# so it is not a uniform sequence:

intervals <- unique(activity$interval)
plot(0:(length(intervals) - 1), intervals, type = 'l', ylim = c(0, 2500))

# Remedy this by converting to time, then to hours after midnight:

times <- strptime(sprintf("%04d", intervals), "%H%M")
hours <- difftime(times, strptime("0000", "%H%M")) / 3600

plot(0:(length(hours) - 1), hours, type = 'l', ylim = c(0, 25))

# Just in case the data are not entirely orderly:

as.hour <- function(intervals) {
    times <- strptime(sprintf("%04d", intervals), "%H%M")
    hours <- difftime(times, strptime("0000", "%H%M")) / 3600
    return(hours)
}

activity$hour = as.hour(activity$interval)
```

## What is mean total number of steps taken per day?

``` {r}
steps_per_day = tapply(activity$steps, 
                       activity$date, 
                       function(x) sum(x, na.rm = TRUE))

summary(steps_per_day)

hist(steps_per_day, 
     main = "Distribution of Total Reported Steps Taken Per Day", 
     xlab = "Reported Steps per Day", 
     ylab = "Days", 
     breaks = 25, xlim = c(0, 25000), ylim = c(0, 10))

sprintf("Mean number of reported steps per day is %4.0f.", 
        mean(steps_per_day))
sprintf("Median number of reported steps per day is %4.0f.",
        median(steps_per_day))
```

## What is the average daily activity pattern?

``` {r}
steps_per_interval = tapply(activity$steps, 
                            activity$hour, 
                            function(x) mean(x, na.rm = TRUE))

plot(as.numeric(names(steps_per_interval)), 
     steps_per_interval, 
     type = "l", 
     main = "Average (Over 61 Days) Reported Steps in Five-Minute Interval", 
     xlab = "Interval Start Time (Hours After Midnight)", 
     ylab = "Average Number of Steps in Interval",
     xlim = c(0, 25))

summary(steps_per_interval)

wm <- which.max(steps_per_interval)
max_minutes <- as.numeric(names(wm)[1]) * 60
maxH <- as.integer(max_minutes %/% 60)
maxM <- as.integer(max_minutes %% 60)

sprintf("The five-minute interval beginning at %02d:%02d has the highest number of reported steps taken (%3.2f), averaged across the days in the dataset.", maxH, maxM, steps_per_interval[wm])
```

## Imputing missing values

``` {r}
activitySummary <- summary(activity)
print(activitySummary)

sprintf("There are %d NAs in activity$steps and none elsewhere.",
        as.integer(strsplit(activitySummary[7, 1], ":")[[1]][2]))

# Is average over day a viable way to imput missing data?

withNA <- droplevels(subset(activity, is.na(steps)))

table(withNA$date)

# Dates with NAs are missing all data, so no.

# Mean over interval will work

activityImputed <- activity
activityImputed$steps[activityImputed$date %in% levels(withNA$date)] <-
    steps_per_interval

steps_per_day_imputed = tapply(activityImputed$steps, activityImputed$date, sum)

hist(steps_per_day_imputed, 
     main = "Distribution of Total (Imputed) Steps Taken Per Day", 
     xlab = "Steps per Day", 
     ylab = "Days", 
     breaks = 25, xlim = c(0, 25000), ylim = c(0, 20))

summary(steps_per_day_imputed)

sprintf("Mean number of (imputed) steps per day is %4.0f.", 
        mean(steps_per_day_imputed))
sprintf("Median number of (imputed) steps per day is %4.0f.",
        median(steps_per_day_imputed))
```

## Are there differences in activity patterns between weekdays and weekends?

``` {r}
activityImputed$weekend <- sapply(as.Date(activityImputed$date), 
                                  function(x) 
                                     weekdays(x) %in% 
                                     c("Saturday", 
                                       "Sunday"))
wkends = subset(activityImputed, weekend == TRUE)
wkdays = subset(activityImputed, weekend == FALSE)
steps_per_interval_weekdays = tapply(wkdays$steps, 
                                     wkdays$hour, 
                                     mean)
steps_per_interval_weekends = tapply(wkends$steps, 
                                     wkends$hour, 
                                     mean)
require(ggplot2)

final <- 
    rbind.data.frame(data.frame(steps = steps_per_interval_weekends, 
                                hour = as.numeric(
                                    names(steps_per_interval_weekends)),
                                day = "Weekend"),
                     data.frame(steps = steps_per_interval_weekdays,
                                hour = as.numeric(
                                    names(steps_per_interval_weekdays)), 
                                day = "Weekday"))

str(final)

qplot(hour, steps, data = final, geom = "line") + 
    facet_grid(day ~ .) + 
    labs(x = "Interval Start Time (Hours After Midnight)", 
         y = "Average Number of Steps Taken in Interval", 
         title = "Average Steps Taken in Five-Minute Interval")
```

